export const componentStyles = {
  menuItem: {
    display: 'flex',
    alignItems: 'center',
    padding: '10px 16px',
    cursor: 'pointer',
    transition: 'all 0.2s',
    borderRadius: 6,
    margin: '2px 8px',
    color: 'var(--api-text-secondary)',
  },
  menuItemActive: {
    backgroundColor: 'rgba(22, 119, 255, 0.1)',
    color: 'var(--api-primary)',
    fontWeight: 500,
  },
  menuItemHover: {
    backgroundColor: 'var(--api-bg-secondary)',
    color: 'var(--api-text-primary)',
  },
  categoryTitle: {
    padding: '12px 16px 8px',
    fontSize: 12,
    fontWeight: 600,
    textTransform: 'uppercase' as const,
    letterSpacing: 0.5,
    color: 'var(--api-text-tertiary)',
  },
  codeBlock: {
    backgroundColor: 'var(--api-code-bg)',
    borderRadius: 8,
    padding: 16,
    margin: '16px 0',
    overflow: 'auto',
    border: '1px solid var(--api-border-light)',
  },
  codeHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: '8px 12px',
    backgroundColor: 'var(--api-bg-secondary)',
    borderTopLeftRadius: 8,
    borderTopRightRadius: 8,
    borderBottom: '1px solid var(--api-border-light)',
  },
  inlineCode: {
    backgroundColor: 'var(--api-code-bg)',
    padding: '2px 6px',
    borderRadius: 4,
    fontFamily: 'monospace',
    fontSize: 13,
    color: 'var(--api-code-text)',
  },
  table: {
    width: '100%',
    borderCollapse: 'collapse' as const,
    margin: '16px 0',
    fontSize: 14,
  },
  tableHeader: {
    backgroundColor: 'var(--api-bg-secondary)',
    fontWeight: 600,
    textAlign: 'left' as const,
    padding: '12px 16px',
    borderBottom: '2px solid var(--api-border-color)',
    color: 'var(--api-text-primary)',
  },
  tableCell: {
    padding: '12px 16px',
    borderBottom: '1px solid var(--api-border-light)',
    color: 'var(--api-text-secondary)',
  },
  alert: {
    padding: '12px 16px',
    borderRadius: 6,
    margin: '16px 0',
    display: 'flex',
    alignItems: 'flex-start',
    gap: 12,
  },
  alertInfo: {
    backgroundColor: 'rgba(22, 119, 255, 0.1)',
    borderLeft: '4px solid var(--api-primary)',
  },
  alertSuccess: {
    backgroundColor: 'rgba(82, 196, 26, 0.1)',
    borderLeft: '4px solid var(--api-success)',
  },
  alertWarning: {
    backgroundColor: 'rgba(250, 173, 20, 0.1)',
    borderLeft: '4px solid var(--api-warning)',
  },
};
